[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/v1/*"
  to = "https://hotel-management-backend-s0s0.onrender.com/api/v1/:splat"
  status = 200
  force = true
