import { QuestionConfig, StayMatchPreferences } from './types';

export const INITIAL_PREFERENCES: StayMatchPreferences = {
  purpose: undefined,
  budget: undefined,
  guests: undefined,
  bedType: undefined,
  amenities: [],
  environment: [],
};

export const STAY_MATCH_QUESTIONS: QuestionConfig[] = [
  {
    id: 'purpose',
    step: 1,
    title: 'What is the primary occasion for your stay?',
    subtitle: 'We tailor room selections and amenities to match your journey.',
    type: 'single-card',
    required: true,
    options: [
      { value: 'Business', label: 'Business', icon: '💼', description: 'Productivity focused, quiet spaces & high-speed internet' },
      { value: 'Leisure', label: 'Leisure', icon: '🌴', description: 'Relaxation and comfort for a serene break' },
      { value: 'Family Vacation', label: 'Family Vacation', icon: '👨‍👩‍👧', description: 'Spacious suites & kid-friendly accommodations' },
      { value: 'Honeymoon', label: 'Honeymoon', icon: '🥂', description: 'Romantic ambiance, luxury views & ultimate privacy' },
      { value: 'Friends', label: 'Friends Getaway', icon: '🎉', description: 'Vibrant socializing spaces & flexible sleeping setups' },
      { value: 'Solo', label: 'Solo Retreat', icon: '🧘', description: 'Cozy, secure, and thoughtfully designed personal sanctuaries' },
    ],
  },
  {
    id: 'budget',
    step: 2,
    title: 'What is your preferred nightly budget?',
    subtitle: 'Select a price tier that aligns with your desired luxury experience.',
    type: 'single-card',
    required: true,
    options: [
      { value: '2000-3000', label: '₹2,000 – ₹3,000', icon: '💎', description: 'Comfortable standard rooms with essential luxury perks' },
      { value: '3000-5000', label: '₹3,000 – ₹5,000', icon: '✨', description: 'Deluxe rooms with superior views & upgraded comfort' },
      { value: '5000+', label: '₹5,000+', icon: '👑', description: 'Premium suites & presidential accommodations with bespoke amenities' },
    ],
  },
  {
    id: 'guests',
    step: 3,
    title: 'How many guests will be staying?',
    subtitle: 'We will ensure ample bedding and living space for everyone.',
    type: 'number-selector',
    required: true,
    options: [
      { value: 1, label: '1 Guest', icon: '👤' },
      { value: 2, label: '2 Guests', icon: '👥' },
      { value: 3, label: '3 Guests', icon: '👨‍👩‍👦' },
      { value: 4, label: '4+ Guests', icon: '👨‍👩‍👧‍👦' },
    ],
  },
  {
    id: 'bedType',
    step: 4,
    title: 'Do you have a bed arrangement preference?',
    subtitle: 'Choose your ideal bedding setup for a restful night.',
    type: 'single-card',
    required: true,
    options: [
      { value: 'King', label: 'King Bed', icon: '👑', description: 'Expansive plush king mattress for maximum comfort' },
      { value: 'Double', label: 'Double Bed', icon: '🛏️', description: 'Standard couple or spacious solo comfort' },
      { value: 'Twin', label: 'Twin Beds', icon: '🛋️', description: 'Two separate single beds ideal for travel companions' },
      { value: 'Single', label: 'Single Bed', icon: '🛌', description: 'Cozy single bed for individual travelers' },
      { value: 'No Preference', label: 'No Preference', icon: '✦', description: 'Any comfortable quality bed arrangement' },
    ],
  },
  {
    id: 'amenities',
    step: 5,
    title: 'Which amenities are essential for your stay?',
    subtitle: 'Select all features you would like included with your room.',
    type: 'checkbox-grid',
    required: false,
    options: [
      { value: 'Free WiFi', label: 'Free WiFi', icon: '📶' },
      { value: 'Breakfast Included', label: 'Breakfast Included', icon: '☕' },
      { value: 'Balcony', label: 'Private Balcony', icon: '🌅' },
      { value: 'Bathtub', label: 'Soak Bathtub', icon: '🛁' },
      { value: 'Parking', label: 'Valet Parking', icon: '🚗' },
      { value: 'Air Conditioning', label: 'Air Conditioning', icon: '❄️' },
      { value: 'Swimming Pool', label: 'Pool Access', icon: '🏊' },
      { value: 'Gym', label: 'Fitness Center', icon: '💪' },
      { value: 'Room Service', label: '24/7 Room Service', icon: '🛎️' },
    ],
  },
  {
    id: 'environment',
    step: 6,
    title: 'What is your preferred room atmosphere?',
    subtitle: 'Pick the environment and setting attributes that matter most to you.',
    type: 'checkbox-grid',
    required: false,
    options: [
      { value: 'Quiet', label: 'Quiet & Soundproof', icon: '🌙' },
      { value: 'Luxury', label: 'High Luxury', icon: '✨' },
      { value: 'Scenic View', label: 'Scenic / Ocean View', icon: '🌊' },
      { value: 'Near Elevator', label: 'Convenient Access (Near Elevator)', icon: '🚪' },
      { value: 'High Floor', label: 'High Floor & Panorama', icon: '🏙️' },
      { value: 'Family Friendly', label: 'Family & Safe Setting', icon: '🛡️' },
    ],
  },
];
