-- Add missing columns to reviews table
ALTER TABLE public.reviews
ADD COLUMN IF NOT EXISTS title TEXT,
ADD COLUMN IF NOT EXISTS stay_type TEXT,
ADD COLUMN IF NOT EXISTS room_type TEXT,
ADD COLUMN IF NOT EXISTS country TEXT,
ADD COLUMN IF NOT EXISTS avatar_url TEXT,
ADD COLUMN IF NOT EXISTS guest_name TEXT;

-- Drop existing seed reviews if any to start fresh
DELETE FROM public.reviews WHERE rating >= 4.5;

-- Insert 15 realistic reviews
INSERT INTO public.reviews (guest_name, country, avatar_url, rating, title, comment, stay_type, room_type, created_at) VALUES
('James Anderson', 'United Kingdom', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150', 5.0, 'Exceptional service from check-in to check-out.', 'Our stay was absolutely magnificent. From the warm welcome at the reception to the impeccable room service, every detail was perfect. The concierge team went above and beyond to arrange our city tours.', 'Couple', 'The Presidential Suite', '2026-05-15 10:00:00'),
('Sophia Martinez', 'Spain', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150', 4.8, 'Stunning ocean view and luxurious rooms.', 'Waking up to the sunrise over the ocean from our balcony was breath-taking. The suite was incredibly spacious, and the housekeeping staff ensured it was pristine twice a day. Truly a five-star experience.', 'Family', 'Premium Deluxe', '2026-06-02 14:30:00'),
('David Chen', 'Singapore', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150', 5.0, 'Perfect honeymoon experience.', 'We chose this hotel for our honeymoon and couldn''t be happier. The staff left champagne and rose petals in our suite. The private dining experience they arranged for us was the highlight of our trip.', 'Honeymoon', 'Honeymoon Suite', '2026-06-10 11:20:00'),
('Emma Wilson', 'Australia', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150', 4.7, 'Excellent spa and wellness facilities.', 'I visited for a weekend wellness retreat. The Elite Fitness Centre has state-of-the-art equipment, and my massage at the spa was heavenly. The perfect place to unwind and recharge.', 'Solo', 'Deluxe Room', '2026-06-15 09:45:00'),
('Michael Roberts', 'United States', 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=150', 4.9, 'Amazing breakfast buffet.', 'The culinary offerings here are unmatched. The breakfast buffet had an incredible spread of international and local cuisines. The chefs were accommodating to dietary requirements. Will definitely return!', 'Business', 'Executive Room', '2026-06-20 08:30:00'),
('Isabella Rossi', 'Italy', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150', 5.0, 'Staff were extremely professional.', 'Every single staff member greeted us with a smile and anticipated our needs before we even asked. The level of training and dedication to guest satisfaction is evident in every interaction.', 'Family', 'Family Suite', '2026-06-25 16:15:00'),
('Oliver Schmidt', 'Germany', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150', 4.6, 'Best luxury hotel experience in the city.', 'Having stayed at many high-end hotels globally, I can confidently say this ranks in my top three. The architecture is stunning, the location is central, and the exclusive lounge access was well worth it.', 'Business', 'Standard Room', '2026-06-28 19:00:00'),
('Amelia Taylor', 'Canada', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150', 4.8, 'An oasis of tranquility.', 'Despite being in the heart of the city, the hotel feels like a peaceful sanctuary. The soundproofing in the rooms is excellent, ensuring a perfect night''s sleep on their premium mattresses.', 'Solo', 'Deluxe Room', '2026-07-01 10:10:00'),
('Lucas Dubois', 'France', 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=150', 5.0, 'Unparalleled attention to detail.', 'From the personalized welcome note to the turndown service with artisan chocolates, the attention to detail is what sets this property apart. The concierge secured reservations at fully booked restaurants for us.', 'Couple', 'Junior Suite', '2026-07-02 12:40:00'),
('Mia Suzuki', 'Japan', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150', 4.9, 'Exceeded all our expectations.', 'We booked the Royal Suite for a special anniversary. It was breath-taking. The panoramic views from the terrace and the grand piano made our evenings magical. The butler service was flawless.', 'Couple', 'The Royal Suite', '2026-07-03 09:20:00'),
('Alexander Ivanov', 'Russia', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150', 4.7, 'Superb business facilities.', 'The meeting rooms and business center were equipped with everything I needed for my conference. High-speed internet was reliable throughout the property. The executive lounge was perfect for networking.', 'Business', 'Executive Room', '2026-07-04 14:00:00'),
('Charlotte Brown', 'New Zealand', 'https://images.unsplash.com/photo-1554151228-14d9def656e4?w=150', 4.8, 'A perfect family getaway.', 'Traveling with three kids can be challenging, but the hotel made it effortless. The Family Suite gave us plenty of space, and the kids loved the indoor pool. Babysitting services were arranged promptly.', 'Family', 'Family Suite', '2026-07-05 11:30:00'),
('William Garcia', 'Mexico', 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=150', 5.0, 'Incredible dining experiences.', 'We dined at all three signature restaurants on the property, and each was a culinary masterpiece. The sommelier''s wine pairings at the fine dining venue were exceptional.', 'Couple', 'Premium Deluxe', '2026-07-06 20:45:00'),
('Emily White', 'South Africa', 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150', 4.9, 'Luxurious amenities and decor.', 'The aesthetic of the hotel perfectly balances modern luxury with classic elegance. The marble bathrooms with premium toiletries made me feel like royalty. Highly recommended.', 'Solo', 'Standard Room', '2026-07-07 08:15:00'),
('Mohammed Al-Fayed', 'UAE', 'https://images.unsplash.com/photo-1618077360395-f3068be8e001?w=150', 5.0, 'The ultimate penthouse experience.', 'We stayed in the Penthouse Suite and it was nothing short of spectacular. The private pool, dedicated elevator, and the 24/7 staff catering to our every whim made this a trip of a lifetime.', 'Family', 'Penthouse Suite', '2026-07-08 17:50:00');
