import { Room, Booking, User, Testimonial, ChartDataPoint } from "@/types";

// ─── Mock Rooms ───────────────────────────────────────────────────────────────
export const mockRooms: Room[] = [
  {
    id: "cccccccc-cccc-cccc-cccc-cccccccccccc",
    name: "Classic Standard Room",
    type: "standard",
    status: "available",
    pricePerNight: 149,
    size: 320,
    maxGuests: 2,
    bedType: "Queen Bed",
    floor: 3,
    description: "A cozy and elegantly designed room with modern amenities.",
    longDescription: "Our Classic Standard Room offers a perfect blend of comfort and style. Featuring a plush queen-size bed, modern en-suite bathroom, and stunning views, this room is your ideal retreat after a day of exploration. The room is equipped with all essential amenities to ensure a comfortable stay.",
    amenities: ["Free WiFi", "Smart TV", "Mini Bar", "Air Conditioning", "Room Service", "In-room Safe"],
    images: [
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800",
      "https://images.unsplash.com/photo-1631049552057-403cdb8f0658?w=800",
    ],
    rating: 4.5,
    reviewCount: 128,
    featured: false,
  },
  {
    id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    name: "Deluxe Ocean View",
    type: "deluxe",
    status: "available",
    pricePerNight: 299,
    size: 520,
    maxGuests: 2,
    bedType: "King Bed",
    floor: 7,
    description: "Wake up to breathtaking ocean views from your private balcony.",
    longDescription: "Indulge in the ultimate luxury with our Deluxe Ocean View room. Perched on the 7th floor, you'll be greeted each morning with panoramic views of the shimmering ocean. The room features a king-size bed with premium linens, a private balcony, elegant marble bathroom with soaking tub, and a dedicated seating area.",
    amenities: ["Free WiFi", "Smart TV", "Mini Bar", "Air Conditioning", "Room Service", "Private Balcony", "Ocean View", "Soaking Tub", "In-room Safe", "Espresso Machine"],
    images: [
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800",
    ],
    rating: 4.8,
    reviewCount: 247,
    featured: true,
  },
  {
    id: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
    name: "Premium Suite",
    type: "suite",
    status: "available",
    pricePerNight: 549,
    size: 850,
    maxGuests: 4,
    bedType: "King Bed + Sofa Bed",
    floor: 12,
    description: "A spacious suite with separate living area and premium amenities.",
    longDescription: "The Premium Suite is a sanctuary of luxury spanning 850 square feet. Featuring a separate living room and dining area, master bedroom with king-size bed, two full bathrooms, and a wrap-around terrace. Enjoy personalized butler service, a fully-stocked bar, and exclusive access to the Executive Lounge.",
    amenities: ["Free WiFi", "2 Smart TVs", "Full Bar", "Air Conditioning", "24/7 Butler Service", "Private Terrace", "City & Ocean View", "Whirlpool Tub", "In-room Safe", "Espresso Machine", "Executive Lounge Access", "Dining Area"],
    images: [
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800",
      "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800",
    ],
    rating: 4.9,
    reviewCount: 89,
    featured: true,
  },
  {
    id: "dddddddd-dddd-dddd-dddd-dddddddddddd",
    name: "Presidential Suite",
    type: "presidential",
    status: "available",
    pricePerNight: 1299,
    size: 1800,
    maxGuests: 6,
    bedType: "2 King Beds",
    floor: 20,
    description: "The pinnacle of luxury — our most exclusive accommodation.",
    longDescription: "The Presidential Suite represents the apex of luxury hospitality. Spanning the entire top floor at 1,800 square feet, this exquisite retreat features two master bedrooms, a grand living room, private dining room, fully-equipped gourmet kitchen, and a rooftop terrace with panoramic 360° views. Personal butler, private chef available on request.",
    amenities: ["Free WiFi", "3 Smart TVs", "Gourmet Kitchen", "Private Rooftop Terrace", "Personal Butler", "Chef on Request", "Panoramic Views", "Steam Room", "Home Theater", "Private Pool Access", "Executive Lounge Access", "Limousine Transfer"],
    images: [
      "https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800",
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800",
    ],
    rating: 5.0,
    reviewCount: 34,
    featured: true,
  },
  {
    id: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",
    name: "Garden View Standard",
    type: "standard",
    status: "occupied",
    pricePerNight: 169,
    size: 340,
    maxGuests: 2,
    bedType: "Double Bed",
    floor: 2,
    description: "Peaceful garden views with a serene and calm atmosphere.",
    longDescription: "Wake up to lush garden views and the soothing sounds of nature. Our Garden View Standard room offers a tranquil escape with a comfortable double bed, modern amenities, and direct garden access for morning strolls.",
    amenities: ["Free WiFi", "Smart TV", "Mini Bar", "Air Conditioning", "Room Service", "Garden View", "In-room Safe"],
    images: [
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800",
    ],
    rating: 4.4,
    reviewCount: 92,
    featured: false,
  },
  {
    id: "ffffffff-ffff-ffff-ffff-ffffffffffff",
    name: "Executive Deluxe",
    type: "deluxe",
    status: "available",
    pricePerNight: 379,
    size: 620,
    maxGuests: 3,
    bedType: "King Bed",
    floor: 9,
    description: "Business-ready luxury with dedicated workspace and lounge access.",
    longDescription: "Designed for the discerning business traveler, the Executive Deluxe room combines sophisticated styling with practical business amenities. Features a dedicated workspace, high-speed WiFi, Executive Lounge access, and premium city views.",
    amenities: ["Free WiFi", "Smart TV", "Mini Bar", "Air Conditioning", "Room Service", "Executive Lounge Access", "Dedicated Workspace", "In-room Safe", "Espresso Machine", "City View"],
    images: [
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800",
    ],
    rating: 4.7,
    reviewCount: 163,
    featured: false,
  },
  {
    id: "11111112-1111-1111-1111-111111111111",
    name: "Honeymoon Suite",
    type: "suite",
    status: "reserved",
    pricePerNight: 699,
    size: 920,
    maxGuests: 2,
    bedType: "King Bed",
    floor: 15,
    description: "Romantic suite with rose petals, champagne, and ocean views.",
    longDescription: "Create unforgettable memories in our Honeymoon Suite. Designed for romance, this stunning suite features a private oceanfront terrace, a luxurious four-poster king bed, a couples' spa bath, and complimentary champagne on arrival. Special romantic packages available.",
    amenities: ["Free WiFi", "Smart TV", "Champagne on Arrival", "Air Conditioning", "24/7 Room Service", "Private Terrace", "Couples Spa Bath", "Ocean View", "Rose Petal Turndown", "Romantic Packages"],
    images: [
      "https://images.unsplash.com/photo-1568495248636-6432b97bd949?w=800",
    ],
    rating: 4.9,
    reviewCount: 57,
    featured: true,
  },
  {
    id: "22222223-2222-2222-2222-222222222222",
    name: "Family Deluxe Room",
    type: "deluxe",
    status: "available",
    pricePerNight: 329,
    size: 680,
    maxGuests: 5,
    bedType: "2 Queen Beds",
    floor: 5,
    description: "Spacious family room with all amenities for a perfect family stay.",
    longDescription: "The Family Deluxe Room is thoughtfully designed for families traveling together. Featuring two queen beds, a separate kids' play corner, a large bathroom with amenities for children, and garden views. Child-friendly menus and babysitting services available.",
    amenities: ["Free WiFi", "2 Smart TVs", "Mini Bar", "Air Conditioning", "Room Service", "Kids Play Corner", "Garden View", "In-room Safe", "Baby Cot Available", "Family Packages"],
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800",
    ],
    rating: 4.6,
    reviewCount: 198,
    featured: false,
  },
];

// ─── Mock Bookings ────────────────────────────────────────────────────────────
export const mockBookings: Booking[] = [
  { id: "BK-2401", guestName: "James Morrison", guestEmail: "james@email.com", guestPhone: "+1-555-0101", roomId: "room-002", roomName: "Deluxe Ocean View", roomType: "deluxe", checkIn: "2024-12-10", checkOut: "2024-12-14", nights: 4, guests: 2, totalAmount: 1196, status: "confirmed", createdAt: "2024-12-01" },
  { id: "BK-2402", guestName: "Sophia Chen", guestEmail: "sophia@email.com", guestPhone: "+1-555-0102", roomId: "room-003", roomName: "Premium Suite", roomType: "suite", checkIn: "2024-12-11", checkOut: "2024-12-13", nights: 2, guests: 2, totalAmount: 1098, status: "checked-in", createdAt: "2024-12-02" },
  { id: "BK-2403", guestName: "Robert Williams", guestEmail: "robert@email.com", guestPhone: "+1-555-0103", roomId: "room-001", roomName: "Classic Standard", roomType: "standard", checkIn: "2024-12-09", checkOut: "2024-12-12", nights: 3, guests: 1, totalAmount: 447, status: "checked-out", createdAt: "2024-11-28" },
  { id: "BK-2404", guestName: "Emma Thompson", guestEmail: "emma@email.com", guestPhone: "+1-555-0104", roomId: "room-007", roomName: "Honeymoon Suite", roomType: "suite", checkIn: "2024-12-15", checkOut: "2024-12-18", nights: 3, guests: 2, totalAmount: 2097, status: "pending", createdAt: "2024-12-05" },
  { id: "BK-2405", guestName: "Michael Davis", guestEmail: "michael@email.com", guestPhone: "+1-555-0105", roomId: "room-004", roomName: "Presidential Suite", roomType: "presidential", checkIn: "2024-12-20", checkOut: "2024-12-25", nights: 5, guests: 4, totalAmount: 6495, status: "confirmed", createdAt: "2024-12-03" },
  { id: "BK-2406", guestName: "Isabella Martinez", guestEmail: "isabella@email.com", guestPhone: "+1-555-0106", roomId: "room-008", roomName: "Family Deluxe", roomType: "deluxe", checkIn: "2024-12-12", checkOut: "2024-12-16", nights: 4, guests: 4, totalAmount: 1316, status: "confirmed", createdAt: "2024-12-04" },
  { id: "BK-2407", guestName: "William Johnson", guestEmail: "will@email.com", guestPhone: "+1-555-0107", roomId: "room-006", roomName: "Executive Deluxe", roomType: "deluxe", checkIn: "2024-12-08", checkOut: "2024-12-10", nights: 2, guests: 1, totalAmount: 758, status: "cancelled", createdAt: "2024-11-25" },
  { id: "BK-2408", guestName: "Olivia Brown", guestEmail: "olivia@email.com", guestPhone: "+1-555-0108", roomId: "room-005", roomName: "Garden View Standard", roomType: "standard", checkIn: "2024-12-13", checkOut: "2024-12-17", nights: 4, guests: 2, totalAmount: 676, status: "confirmed", createdAt: "2024-12-06" },
];

// ─── Mock Users ───────────────────────────────────────────────────────────────
export const mockUsers: User[] = [
  { id: "u-001", name: "Alexandra Reed", email: "alex@hospitalityhub.com", role: "manager", phone: "+1-555-1001", joinedAt: "2023-01-15", status: "active" },
  { id: "u-002", name: "Marcus Knight", email: "marcus@hospitalityhub.com", role: "receptionist", phone: "+1-555-1002", joinedAt: "2023-03-20", status: "active" },
  { id: "u-003", name: "Priya Sharma", email: "priya@hospitalityhub.com", role: "staff", phone: "+1-555-1003", joinedAt: "2023-06-10", status: "active" },
  { id: "u-004", name: "Lucas Fontaine", email: "lucas@hospitalityhub.com", role: "receptionist", phone: "+1-555-1004", joinedAt: "2023-08-01", status: "active" },
  { id: "u-005", name: "Sofia Vasquez", email: "sofia@hospitalityhub.com", role: "staff", phone: "+1-555-1005", joinedAt: "2024-01-10", status: "active" },
  { id: "u-006", name: "Thomas Blake", email: "thomas@hospitalityhub.com", role: "staff", phone: "+1-555-1006", joinedAt: "2024-02-15", status: "inactive" },
  { id: "u-007", name: "Hannah Schmidt", email: "hannah@hospitalityhub.com", role: "receptionist", phone: "+1-555-1007", joinedAt: "2024-03-05", status: "active" },
];

// ─── Mock Testimonials ────────────────────────────────────────────────────────
export const mockTestimonials: Testimonial[] = [
  { id: "t-1", name: "Sarah Mitchell", role: "Business Traveler", avatar: "SM", rating: 5, title: "Amazing", stayType: "Business", roomType: "Presidential Suite", country: "US", comment: "Absolutely breathtaking experience. The Presidential Suite exceeded every expectation. The butler service was impeccable, and the views from the rooftop were simply unforgettable.", date: "November 2024" },
  { id: "t-2", name: "David & Laura Chen", role: "Honeymooners", avatar: "DC", rating: 5, title: "Perfect", stayType: "Honeymoon", roomType: "Honeymoon Suite", country: "CA", comment: "We chose Hospitality Hub for our honeymoon and it was the best decision. The Honeymoon Suite was magical — rose petals, champagne, and the most spectacular ocean view. Pure perfection.", date: "October 2024" },
  { id: "t-3", name: "James O'Brien", role: "Family Vacation", avatar: "JO", rating: 5, title: "Great", stayType: "Family", roomType: "Family Suite", country: "UK", comment: "Traveled with my family of four and the staff made every moment special. Kids loved the pool area and the family dining experience was exceptional. We'll definitely return.", date: "September 2024" },
  { id: "t-4", name: "Dr. Amelia Foster", role: "Conference Guest", avatar: "AF", rating: 4, title: "Good", stayType: "Business", roomType: "Standard Room", country: "AU", comment: "Outstanding facilities for our medical conference. The Executive Lounge access was perfect, high-speed WiFi never faltered, and the concierge team was proactive and helpful throughout.", date: "October 2024" },
  { id: "t-5", name: "Marco Pellegrini", role: "Leisure Guest", avatar: "MP", rating: 5, title: "Excellent", stayType: "Solo", roomType: "Deluxe Room", country: "IT", comment: "The spa experience alone is worth the visit. Coupled with the world-class restaurant and the Deluxe Ocean View room, this was the most rejuvenating holiday I have ever had.", date: "November 2024" },
];

// ─── Chart Data ───────────────────────────────────────────────────────────────
export const bookingTrendData: ChartDataPoint[] = [
  { name: "Jan", bookings: 45, revenue: 18500 },
  { name: "Feb", bookings: 52, revenue: 22100 },
  { name: "Mar", bookings: 78, revenue: 31200 },
  { name: "Apr", bookings: 91, revenue: 38900 },
  { name: "May", bookings: 103, revenue: 44700 },
  { name: "Jun", bookings: 127, revenue: 56300 },
  { name: "Jul", bookings: 158, revenue: 72100 },
  { name: "Aug", bookings: 172, revenue: 81500 },
  { name: "Sep", bookings: 134, revenue: 61200 },
  { name: "Oct", bookings: 119, revenue: 53400 },
  { name: "Nov", bookings: 143, revenue: 65800 },
  { name: "Dec", bookings: 189, revenue: 94200 },
];

export const occupancyData = [
  { name: "Standard", value: 78, color: "#3B82F6" },
  { name: "Deluxe", value: 85, color: "#C9A84C" },
  { name: "Suite", value: 62, color: "#10B981" },
  { name: "Presidential", value: 90, color: "#8B5CF6" },
];
